version: "3.7"

volumes:
  postgres:

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  web_app: &web_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./bin/rails server -p 3000 -b 0.0.0.0
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      - DATABASE_HOST="postgres"
      - DATABASE_USERNAME="postgres"
      - DATABASE_PASSWORD="password"
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:3000 || exit 1"]
